# Generated by Django 2.0 on 2018-08-13 10:07

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0065_auto_20180809_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('respond_hours', models.BigIntegerField()),
                ('plan_within', models.BigIntegerField()),
                ('resolution_hours', models.BigIntegerField()),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djconnectwise.TicketPriority')),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djconnectwise.Sla')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
