# Generated by Django 2.0 on 2018-08-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0066_slapriority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sla',
            options={'verbose_name_plural': 'SLAs'},
        ),
        migrations.AlterModelOptions(
            name='slapriority',
            options={'verbose_name_plural': 'SLA Priorities'},
        ),
    ]
