# Generated by Django 2.0 on 2018-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0070_mycompanyother'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardstatus',
            name='escalation_status',
            field=models.CharField(blank=True, choices=[('NotResponded', 'Not Responded'), ('Responded', 'Responded'), ('ResolutionPlan', 'Resolution Plan'), ('Resolved', 'Resolved'), ('NoEscalation', 'No Escalation')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='do_not_escalate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
