# Generated by Django 2.1 on 2019-05-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0084_auto_20190404_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
