# Generated by Django 2.1 on 2019-07-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0087_worktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='inactive_flag',
            field=models.BooleanField(default=False),
        ),
    ]
