# Generated by Django 2.1 on 2019-07-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0090_auto_20190711_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='work_type',
        ),
    ]
