# Generated by Django 2.1 on 2019-07-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0098_auto_20190718_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_tickets', to='djconnectwise.Agreement'),
        ),
    ]
