# Generated by Django 2.1 on 2019-07-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0100_auto_20190718_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djconnectwise.Company'),
        ),
    ]
