# Generated by Django 3.1.2 on 2021-01-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0141_auto_20201215_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcommunication',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Email'), (2, 'Direct'), (3, 'Fax'), (4, 'Cell'), (5, 'Pager'), (6, 'Home'), (7, 'Fax/Home'), (8, 'Home Email'), (11, 'Private Email')], null=True),
        ),
    ]
