# Generated by Django 3.1.7 on 2021-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0151_auto_20210623_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
