# Generated by Django 3.1.7 on 2021-07-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0151_auto_20210623_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='merged_parent_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_parent_tickets', to='djconnectwise.ticket'),
        ),
    ]
