# Generated by Django 3.1.7 on 2021-11-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0156_auto_20210806_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
