# Generated by Django 4.0 on 2022-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0158_auto_20211105_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='budget_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
