# Generated by Django 4.0.7 on 2022-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0167_alter_ticket_is_issue_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
