# Generated by Django 4.0.7 on 2023-03-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0168_ticket_contact_email_address_ticket_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectwiseboard',
            name='timeEntryDiscussionFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectwiseboard',
            name='timeEntryInternalAnalysisFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectwiseboard',
            name='timeEntryResolutionFlag',
            field=models.BooleanField(default=False),
        ),
    ]
