# Generated by Django 4.0.7 on 2023-03-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0169_connectwiseboard_timeentrydiscussionflag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectwiseboard',
            old_name='timeEntryDiscussionFlag',
            new_name='time_entry_discussion_flag',
        ),
        migrations.RenameField(
            model_name='connectwiseboard',
            old_name='timeEntryInternalAnalysisFlag',
            new_name='time_entry_internalanalysis_flag',
        ),
        migrations.RenameField(
            model_name='connectwiseboard',
            old_name='timeEntryResolutionFlag',
            new_name='time_entry_resolution_flag',
        ),
    ]
