# Generated by Django 4.0.10 on 2023-05-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0171_companynotetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNoteTypeTracker',
            fields=[
            ],
            options={
                'db_table': 'djconnectwise_companynotetype',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djconnectwise.companynotetype',),
        ),
    ]
