# Generated by Django 4.2.11 on 2024-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0181_merge_20240523_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysite',
            name='inactive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
