# Generated by Django 4.2.25 on 2025-10-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0190_alter_project_percent_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_level_id', models.IntegerField(blank=True, null=True)),
                ('location_flag', models.BooleanField(default=False)),
                ('client_flag', models.BooleanField(default=False)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djconnectwise.systemlocation')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'System Location',
                'verbose_name_plural': 'System Locations',
            },
        ),
        migrations.CreateModel(
            name='SystemLocationTracker',
            fields=[],
            options={
                'db_table': 'djconnectwise_systemlocation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djconnectwise.systemlocation',),
        ),
        migrations.AddField(
            model_name='ticket',
            name='system_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='djconnectwise.systemlocation'),
        ),
    ]


