# Generated by Django 4.2.25 on 2025-10-31 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0191_systemlocation_and_ticket_system_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='system_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djconnectwise.systemlocation'),
        ),
    ]
