# Generated by Django 4.2.16 on 2026-01-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0192_timeentry_system_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='impact',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='record_type',
            field=models.CharField(blank=True, choices=[('ServiceTicket', 'Service Ticket'), ('ProjectTicket', 'Project Ticket'), ('ProjectIssue', 'Project Issue')], db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resources',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='site_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sla_stage',
            field=models.CharField(blank=True, choices=[('respond', 'Respond'), ('plan', 'Plan'), ('resolve', 'Resolve'), ('resolved', 'Resolved'), ('waiting', 'Waiting')], db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='summary',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
