# Generated by Django 4.2.16 on 2026-03-13 13:16

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0193_alter_ticket_closed_by_alter_ticket_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticket',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='UDFDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('record_type', models.CharField(choices=[('ticket', 'Ticket'), ('project', 'Project'), ('activity', 'Activity'), ('opportunity', 'Opportunity')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('udf_type', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('is_list', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('record_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UDFDefinitionTracker',
            fields=[
            ],
            options={
                'db_table': 'djconnectwise_udfdefinition',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djconnectwise.udfdefinition',),
        ),
    ]
