# Generated by Django 4.2.16 on 2026-03-13 14:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0194_activity_udf_data_opportunity_udf_data_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['udf_data'], name='activity_udf_data_gin'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['udf_data'], name='opportunity_udf_data_gin'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['udf_data'], name='project_udf_data_gin'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['udf_data'], name='ticket_udf_data_gin'),
        ),
    ]
