# Generated by Django 4.2.16 on 2026-03-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0195_activity_activity_udf_data_gin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udfdefinition',
            name='is_list',
        ),
    ]
