# Generated by Django 4.2.25 on 2026-03-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0196_remove_udfdefinition_is_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StandardNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_notes', to='djconnectwise.connectwiseboard')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_notes', to='djconnectwise.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_notes', to='djconnectwise.systemlocation')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DepartmentTracker',
            fields=[
            ],
            options={
                'db_table': 'djconnectwise_department',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djconnectwise.department',),
        ),
        migrations.CreateModel(
            name='StandardNoteTracker',
            fields=[
            ],
            options={
                'db_table': 'djconnectwise_standardnote',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djconnectwise.standardnote',),
        ),
    ]
