# Generated by Django 4.2.25 on 2026-06-01 16:00

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0197_department_standardnote_departmenttracker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('default_flag', models.BooleanField(default=False)),
                ('inactive_flag', models.BooleanField(default=False)),
                ('closed_flag', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Project phase statuses',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectPhaseStatusTracker',
            fields=[
            ],
            options={
                'db_table': 'djconnectwise_projectphasestatus',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djconnectwise.projectphasestatus',),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djconnectwise.projectphasestatus'),
        ),
    ]
