# Generated by Django 4.2.28 on 2026-06-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0198_agreement_application_limit_agreement_bill_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='billing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='billing_method',
            field=models.CharField(blank=True, choices=[('ActualRates', 'Actual Rates'), ('FixedFee', 'Fixed Fee'), ('NotToExceed', 'Not To Exceed'), ('OverrideRate', 'Override Rate')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='estimated_expense_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='estimated_expense_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='estimated_product_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='estimated_product_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='estimated_time_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='estimated_time_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='mark_as_milestone_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='po_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
