# Generated by Django 4.2.16 on 2026-06-15 11:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0198_projectphasestatus_projectphasestatustracker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('default_flag', models.BooleanField(default=False)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgreementTypeTracker',
            fields=[
            ],
            options={
                'db_table': 'djconnectwise_agreementtype',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djconnectwise.agreementtype',),
        ),
        # Destructive swap: the old CharField stored the type *name* (e.g.
        # "Block Time - One time"); those strings can't cast to the new FK's
        # integer column, so drop the column and add a fresh nullable FK.
        # A subsequent cwsync (agreement_type then agreement) repopulates it.
        migrations.RemoveField(
            model_name='agreement',
            name='agreement_type',
        ),
        migrations.AddField(
            model_name='agreement',
            name='agreement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='djconnectwise.agreementtype'),
        ),
    ]
