# Generated by Django 4.2.28 on 2026-06-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0199_agreementtype_agreementtypetracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_tickets', to='djconnectwise.opportunity'),
        ),
    ]
