# Generated by Django 4.2.28 on 2026-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0199_projectphase_billing_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hourly_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='workrole',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
