# Generated by Django 4.2.28 on 2026-06-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0199_agreementtype_agreementtypetracker_and_more'),
        ('djconnectwise', '0200_member_hourly_cost_workrole_hourly_rate'),
    ]

    operations = [
    ]
