# Generated by Django 4.2.16 on 2026-06-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0201_merge_20260622_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_tickets', to='djconnectwise.opportunity'),
        ),
    ]
