# Generated by Django 4.2.28 on 2026-07-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0202_ticket_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='bill_separately_flag',
            field=models.BooleanField(default=False),
        ),
    ]
