# Generated by Django 6.0.7 on 2026-08-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djconnectwise', '0203_projectphase_bill_separately_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationtype',
            name='name',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
